services:
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/static 
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    environment:
      - IS_DOCKER: true
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  media_volume:
  static_volume: